.. comment: This file is intended for global "replace" definitions.

.. |see_cpython| replace:: See CPython documentation:

.. |see_cpython_module| replace::

    *This module implements a subset of the corresponding* :term:`CPython` *module,
    as described below. For more information, refer to the original
    CPython documentation:*

.. |see_cpython_module_zh_cn| replace::

    *如下所述，模块实现了相应* :term:`CPython` *模块的子集。 
    有关更多信息，请参阅原始 CPython 文档：* 