name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - name: sync main branch
      uses: actions/checkout@v2
    # Standard drop-in approach that should work for most people.
    - name: build_docs
      uses: docker://sphinxdoc:sphinx
      run: |
        pip3 install sphinx-intl
        pip3 install sphinx-material
        cd docs
        make html
    - name: sync gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit documentation changes
      run: |
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}